import { useLayoutEffect } from 'react';
import useSEO from '../hooks/useSEO';
import { Calendar } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function Terms() {
  useSEO({
    title: 'Terms of Service | Flasho',
    description: 'Read the Terms and Conditions for using Flasho Home Services.'
  });

  useLayoutEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const lastUpdated = "June 15, 2026";

  return (
    <div className="pt-20 min-h-screen bg-white">
      {/* Header Section */}
      <div className="relative border-b border-gray-100 bg-white overflow-hidden">
        {/* Abstract background subtle glow */}
        <div className="absolute top-0 right-0 w-1/2 h-full bg-gradient-to-l from-primary/5 to-transparent pointer-events-none" />
        <div className="absolute -top-24 -right-24 w-96 h-96 bg-primary/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute top-10 left-10 w-32 h-32 bg-primary/5 rounded-full blur-2xl pointer-events-none" />
        
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 lg:py-20">
          <div className="flex items-center gap-3 text-sm font-medium mb-8">
            <div className="flex items-center gap-2 px-3 py-1.5 bg-gray-50 rounded-full text-gray-600 border border-gray-200 shadow-sm">
              <Link to="/" className="hover:text-primary transition-colors">Home</Link>
              <span className="text-gray-300">/</span>
              <span className="text-gray-900">Legal</span>
            </div>
            <div className="h-4 w-px bg-gray-300"></div>
            <span className="text-primary tracking-widest uppercase text-[11px] font-bold">Terms of Service</span>
          </div>

          <h1 className="text-4xl md:text-5xl lg:text-6xl font-display font-extrabold text-gray-900 mb-6 tracking-tight">
            Terms & Conditions<span className="text-primary">.</span>
          </h1>
          
          <div className="inline-flex items-center gap-2 text-gray-500 text-sm font-medium bg-white/80 backdrop-blur px-4 py-2 rounded-lg border border-gray-100 shadow-sm">
            <Calendar size={16} className="text-primary" />
            <span>Effective Date: {lastUpdated}</span>
          </div>
        </div>
      </div>

      {/* Content Section */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12 lg:py-16">
        <div className="prose prose-lg max-w-none text-gray-700 leading-relaxed font-body text-[15px] sm:text-base">
          <p className="mb-4">This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

          <p className="mb-4">Please read these Terms and Conditions ("Terms") carefully before using the Flasho website, mobile applications, and related digital infrastructure (collectively referred to as the "Platform"). By downloading, installing, accessing, or registering on the Platform, you acknowledge that you have read, understood, and unequivocally agree to be bound by these Terms, along with our Privacy Policy. If you do not agree to these Terms, you are expressly prohibited from using the Platform and must discontinue use immediately.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">1. DEFINITIONS AND INTERPRETATIONS</h2>
          <p className="mb-4">For the purpose of this agreement, unless the context otherwise requires, specific terms shall carry the following meanings. "Flasho", "Company", "We", "Us", or "Our" refers to Flasho Technologies, including its founders, owners, operators, affiliates, successors, permitted assigns, and authorized representatives. The term "Platform" encompasses the Flasho mobile applications available on iOS and Android, websites, APIs, and any associated technological infrastructure facilitating our services. "Customer", "User", or "You" refers to any individual, corporate entity, or organization accessing the Platform to request, book, or consume services. "Agency" refers to any registered independent service provider, registered company, business entity, contractor, or organization officially onboarded onto the Platform to render specific services. "Service Personnel" denotes the specific tradespeople, technicians, electricians, plumbers, cleaners, carpenters, or any other workers deployed, managed, and paid strictly by the registered Agency. Finally, "Service(s)" means the various home, office, maintenance, repair, installation, cleaning, or other related tasks made available for booking through the Platform.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">2. NATURE AND SCOPE OF THE PLATFORM</h2>
          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">2.1 Intermediary Marketplace</h3>
          <p className="mb-4">Flasho operates strictly as a technology-based marketplace and digital intermediary. The Platform functions as a bridge, facilitating the connection between Customers seeking specific services and independent Agencies capable of providing them.</p>

          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">2.2 No Employment or Agency Relationship</h3>
          <p className="mb-4">Flasho is not an employer, co-employer, or principal to any Agency or Service Personnel. We do not directly employ, interview, supervise, manage, control, or monitor the daily activities of the Service Personnel. All Agencies operate as independent business entities and retain complete control over their internal operations, hiring practices, and service delivery methods.</p>

          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">2.3 Disclaimer of Contractor Relationship</h3>
          <p className="mb-4">Absolutely nothing in these Terms, nor your use of the Platform, shall be construed to create an employment relationship, partnership, joint venture, franchise, or agency relationship between Flasho and any Customer, Agency, or Service Personnel.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">3. USER ELIGIBILITY</h2>
          <p className="mb-4">To lawfully access and utilize the Platform, you strictly must be at least eighteen years of age, or the age of legal majority in your applicable jurisdiction. You must possess the legal capacity to enter into a binding contract under the Indian Contract Act, 1872. Furthermore, you are required to provide truthful, current, and verifiable information during the registration process and comply with all applicable local, state, and national laws while using the Platform. Flasho reserves the absolute right to refuse access, terminate accounts, or permanently ban users who are found to be in violation of these eligibility criteria without any prior notice.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">4. ACCOUNT REGISTRATION AND SECURITY</h2>
          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">4.1 Registration Requirements</h3>
          <p className="mb-4">Accessing the core features of the Platform requires the creation of a user account. This process mandates the submission of a valid, active mobile phone number subject to OTP verification, an email address, and other necessary demographic details.</p>

          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">4.2 Account Security</h3>
          <p className="mb-4">You are entirely responsible for safeguarding your login credentials. Any activity occurring under your registered account, whether authorized by you or not, is your sole responsibility. You agree to notify Flasho immediately upon discovering any unauthorized access, breach of security, or suspected fraudulent activity pertaining to your account.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">5. SCOPE OF SERVICES</h2>
          <p className="mb-4">Through the Platform, Customers may request various professional services, which currently include but are not strictly limited to electrical maintenance and repairs, plumbing and pipe-fitting services, carpentry and woodworking, deep cleaning and routine housekeeping, air conditioning servicing, installation and repair, general appliance repair, painting and surface treatment, pest control and fumigation, and office infrastructure maintenance. Flasho retains the right to add, modify, suspend, or discontinue any specific service category at its sole discretion, based on market demand and Agency availability.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">6. BOOKING AND EXECUTION MECHANISM</h2>
          <p className="mb-4">The facilitation of services occurs through a highly structured lifecycle. Initially, the Customer selects a required service via the Platform interface and inputs exact requirements, preferred scheduling, and the precise geographical location for the service. Flasho’s backend systems then transmit this request to eligible and available Agencies in the vicinity. Once an independent Agency reviews the request and formally accepts the booking, the Agency assigns one or more of its Service Personnel to fulfill the contract. The Service Personnel arrive at the designated location and execute the required tasks. Upon completion, the Customer confirms job fulfillment and finalizes the financial transaction via the Platform.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">7. AGENCY COVENANTS AND OBLIGATIONS</h2>
          <p className="mb-4">Each Agency acting on the Platform formally agrees that it bears the sole and exclusive responsibility for several critical operational aspects. This involves recruitment and vetting, necessitating rigorous background checks, identity verification, and criminal record screening of all deployed Service Personnel. Agencies are also responsible for training and certification, ensuring that deployed personnel possess the requisite skills, trade certifications, and tools necessary to perform the job safely and effectively. Furthermore, Agencies must maintain statutory compliance by strictly adhering to all applicable labor laws, including minimum wage requirements, provident fund contributions, employee state insurance, and workplace safety regulations. Finally, Agencies are tasked with quality assurance, guaranteeing the standard of workmanship and immediately addressing any defects or customer complaints arising from the work performed. Flasho is indemnified and held harmless from any claims, labor disputes, or statutory violations arising directly or indirectly from the Agency's operations.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">8. CUSTOMER COVENANTS AND OBLIGATIONS</h2>
          <p className="mb-4">As a Customer utilizing the Platform, you explicitly agree to supply complete, accurate, and unambiguous details regarding the scope of work and the service location. You must ensure a safe, hazard-free environment for the Service Personnel to operate within and secure all necessary permissions, such as those from building management or housing societies, prior to the arrival of the Service Personnel. You are required to maintain a respectful and professional demeanor at all times. Flasho maintains a strict zero-tolerance policy for verbal abuse, physical harassment, discrimination, or inappropriate behavior toward Service Personnel. Lastly, you agree to settle all undisputed invoices promptly upon completion of the service.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">9. FINANCIAL TERMS AND PAYMENTS</h2>
          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">9.1 Platform Payments</h3>
          <p className="mb-4">To ensure a secure transaction environment and proper dispute resolution, all financial settlements for services booked through Flasho must be processed strictly using the integrated payment gateways provided on the Platform, such as Credit/Debit Cards, UPI, Net Banking, or Platform Wallets.</p>

          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">9.2 Dynamic Pricing</h3>
          <p className="mb-4">The baseline prices quoted on the Platform are estimates. Final pricing may be dynamically adjusted based on variables including, but not limited to, the precise scope of work, geographic location, the urgency of the request including after-hours service, and the physical cost of spare parts or materials required to complete the job.</p>

          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">9.3 Taxation</h3>
          <p className="mb-4">All applicable statutory taxes, including Goods and Services Tax (GST) or any other local levies, will be calculated and appended to the final invoice in accordance with current Indian tax regulations.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">10. REVENUE AND COMMISSION MODEL</h2>
          <p className="mb-4">Flasho sustains its technological infrastructure and marketplace operations by levying a commission or platform fee on successfully completed transactions. By way of illustration, if the final service invoice amounts to ₹1,000, and Flasho’s prevailing commission rate is 15%, Flasho retains ₹150, while ₹850 is remitted to the executing Agency. Flasho reserves the right to dynamically alter its commission structures, platform fees, or subscription models. Notice of material changes will be communicated to registered Agencies and Users within a reasonable timeframe.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">11. NON-CIRCUMVENTION AND OFF-PLATFORM TRANSACTIONS</h2>
          <p className="mb-4">The viability of the Platform relies on transactions being processed securely through our internal systems. Customers and Agencies are strictly prohibited from engaging in off-platform contracting. You may not solicit, offer, or accept direct payments outside of the Flasho ecosystem for any service initially initiated, discovered, or coordinated through the Platform. Violation of this non-circumvention clause constitutes a material breach of these Terms. Flasho reserves the right to immediately terminate the accounts of offending parties, forfeit any pending payouts, and initiate legal proceedings to recover lost revenue and damages.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">12. CANCELLATION FRAMEWORK</h2>
          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">12.1 Customer Initiated Cancellations</h3>
          <p className="mb-4">Regarding customer-initiated cancellations, requests cancelled before an Agency accepts the booking incur no penalty. However, cancellations made after an Agency has accepted the booking, or while Service Personnel are actively in transit, may be subject to a nominal cancellation fee designed to fairly compensate the Agency for lost time and fuel expenditures.</p>

          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">12.2 Agency Initiated Cancellations</h3>
          <p className="mb-4">Agencies are strictly expected to honor all accepted bookings. A pattern of frequent or unjustified cancellations by an Agency will result in punitive actions, which may include algorithmic demotion resulting in reduced marketplace visibility, temporary suspension of their vendor account, or permanent expulsion from the Platform entirely.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">13. REFUNDS AND DISPUTE RESOLUTION</h2>
          <p className="mb-4">Refunds are not guaranteed and are strictly evaluated on a case-by-case basis by our support team. Eligible scenarios for a refund review include demonstrable duplicate charges due to payment gateway errors, the absolute failure of the assigned Service Personnel to arrive at the specified location, or gross negligence resulting in the failure to deliver the agreed-upon core service. All refund requests must be raised via the Platform's designated support channel within 48 hours of the scheduled service date. The issuance of any monetary refund or platform credit remains at the sole and absolute discretion of Flasho management.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">14. USER-GENERATED CONTENT: RATINGS AND REVIEWS</h2>
          <p className="mb-4">To maintain marketplace transparency and service quality, Customers are heavily encouraged to rate and review their service experiences. By submitting a review, you grant Flasho a non-exclusive, perpetual, royalty-free license to display, reproduce, and utilize this feedback across our marketing and promotional channels. Reviews must always be factual and constructive. Flasho retains the unilateral right to remove or redact reviews that contain profanity, hate speech, personally identifiable information, or demonstrably false and defamatory statements. Users found attempting to manipulate the ratings system will face immediate account suspension.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">15. DISCLAIMER OF WARRANTIES</h2>
          <p className="mb-4 uppercase">THE PLATFORM, AND ALL SERVICES FACILITATED THROUGH IT, ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. FLASHO EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TIMELINESS, AND NON-INFRINGEMENT. Flasho does not warrant that the platform will be uninterrupted, error-free, or completely secure. Furthermore, we make no absolute guarantees regarding the reliability, quality, suitability, or safety of the independent Agencies or their respective Service Personnel.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">16. PROPERTY DAMAGE AND INDEMNIFICATION</h2>
          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">16.1 Liability for Damage</h3>
          <p className="mb-4">Any physical damage to the Customer’s property, bodily injury, or material loss directly resulting from the negligence, omission, or willful misconduct of the Service Personnel is exclusively the liability of the executing Agency. Flasho acts merely as a technological conduit and assumes no vicarious liability for the independent actions of third-party contractors.</p>

          <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-2">16.2 Indemnity</h3>
          <p className="mb-4">You agree to defend, indemnify, and hold harmless Flasho, its affiliates, directors, and employees from any claims, damages, obligations, losses, liabilities, costs, or debt arising from your use of and access to the Platform, your violation of any term of this Agreement, or any interactions, disputes, or contracts forged between you and an Agency.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">17. LIMITATION OF LIABILITY</h2>
          <p className="mb-4 uppercase">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE JURISPRUDENCE, IN NO EVENT SHALL FLASHO BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, OR DATA LOSS, ARISING FROM YOUR USE OF THE PLATFORM. Notwithstanding anything to the contrary contained herein, Flasho’s total cumulative liability to you for any cause whatsoever, regardless of the form of the action, will at all times be strictly limited to the specific platform fee or commission actually earned by Flasho for the individual disputed booking.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">18. INTELLECTUAL PROPERTY RIGHTS</h2>
          <p className="mb-4">All source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Platform, collectively known as the Content, as well as the trademarks, service marks, and logos contained therein, are owned by or formally licensed to Flasho. They are fully protected by the copyright and trademark laws of India alongside international conventions. No part of the Platform, Content, or Marks may be copied, reproduced, aggregated, republished, uploaded, publicly displayed, or exploited for any commercial purpose whatsoever without our express prior written permission.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">19. DATA PRIVACY AND TELEMETRY</h2>
          <p className="mb-4">Your privacy is fundamentally critical to our operations. Our collection, storage, and utilization of personal data, location telemetry, and transactional history are meticulously detailed in our separate Privacy Policy. By accepting these Terms, you also provide explicit and informed consent to the data processing practices comprehensively outlined in that accompanying document.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">20. TERMINATION AND SUSPENSION</h2>
          <p className="mb-4">Flasho reserves the unilateral right to suspend, disable, or terminate your access to the Platform at any time, with or without prior notice, if we determine in our sole discretion that you have violated these Terms, engaged in fraudulent or illegal activities, or acted in a manner detrimental to the Platform's ecosystem, its users, or our corporate reputation.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">21. FORWARD-LOOKING MODIFICATIONS</h2>
          <p className="mb-4">The digital marketplace is dynamic, and Flasho reserves the right to independently evolve its business model. This evolution includes, but is not expressly limited to, onboarding independent freelancers alongside corporate Agencies, introducing tiered subscription models for Users such as premium memberships, expanding into new geographical jurisdictions, states, or international territories, and overhauling the underlying technological interface. Such strategic expansions or technological modifications shall not necessitate an immediate amendment to these baseline Terms, which will continue to legally govern all user behavior.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">22. GOVERNING LAW</h2>
          <p className="mb-4">These Terms, and any non-contractual obligations arising out of or in connection with them, shall be governed by, construed, and interpreted strictly in accordance with the laws of the Republic of India, without regard to its conflict of law principles.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">23. DISPUTE RESOLUTION AND ARBITRATION</h2>
          <p className="mb-4">In the event of any dispute, claim, or controversy arising out of or relating to these Terms, the parties shall first attempt to resolve the matter amicably through good faith negotiations for a period of thirty days. If the dispute remains unresolved following this period, it shall be referred to and finally resolved by binding arbitration under the provisions of the Arbitration and Conciliation Act, 1996 as amended. The dispute shall be adjudicated by a sole arbitrator appointed mutually by both parties or, failing agreement, appointed in accordance with the Act. The seat, venue, and place of arbitration shall exclusively be Kolhapur, Maharashtra, India. All arbitration proceedings shall be conducted entirely in the English language.</p>

          <hr className="my-8 border-gray-200" />

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">24. CORPORATE CONTACT INFORMATION</h2>
          <p className="mb-4">If you require clarification regarding these Terms, wish to report a violation, or need to serve legal notices, please contact our designated grievance and support cell. You may reach us via email at <a href="mailto:hello@flasho.services" className="text-primary hover:underline">hello@flasho.services</a> or by telephone at +91 7098251919. Our registered office jurisdiction is located in Kolhapur, Maharashtra, India.</p>

          <hr className="my-8 border-gray-200" />

          <p className="mb-4">By creating an account, booking a service, or otherwise continuing to use the Flasho Platform, you digitally acknowledge that you have thoroughly read, fully comprehended, and unconditionally agreed to be bound by the entirety of these Terms and Conditions.</p>
        </div>
      </div>
    </div>
  );
}
